services:
  cymais-presentation:
    build:
      context: .
      dockerfile: Dockerfile
    image: application-cymais-presentation
    container_name: cymais-presentation
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ${PRESENTATION_SOURCE_PATH}:/source
    restart: unless-stopped
